sudo: required

services:
  - docker

install:
  - mkdir bin && docker build -t ci .

script:
  - echo $TRAVIS_BUILD_DIR
  # - docker run -ti --rm ci bash -c "cd /ffmpeg-static && ./build.sh -j $(($(nproc) + 1)) && ldd bin/ffmpeg && (ldd bin/ffmpeg | grep 'not a dynamic executable')"
  - docker run -v $TRAVIS_BUILD_DIR/bin:/ffmpeg-static/bin -ti --rm ci bash -c "./test.sh && ls -al && ls -al bin"

before_deploy:
  # Set up git user name and tag this commit
  - ls -al
  - ls -al bin
  - git config --local user.name "$EMAIL"
  - git config --local user.email "$USERNAME"
  - git tag "$(date +'%Y%m%d')"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file: bin/*
  skip_cleanup: true