sudo: required

services:
  - docker

install:
  - mkdir bin && docker build -t ci .

script:
  - docker run -v $TRAVIS_BUILD_DIR/bin:/ffmpeg-static/bin -ti --rm ci bash -c "./build.sh -j $(($(nproc) + 1)) && ldd bin/ffmpeg && (ldd bin/ffmpeg | grep 'not a dynamic executable')"
  - ls -al bin
  - ./bin/ffmpeg -version
  - ./bin/ffprobe -version

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "$EMAIL"
  - git config --local user.email "$USERNAME"
  - git tag "$(date +'%Y%m%d')"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  file_glob: true
  file: bin/*
  skip_cleanup: true