sudo: required

services:
  - docker

install:
  - bundle install && chmod -R ug+rwx .
  # - mkdir bin && docker build -t ci .

script:
  - whoami
  # - docker run -v $TRAVIS_BUILD_DIR/bin:/ffmpeg-static/bin -ti --rm ci bash -c "./build.sh -j $(($(nproc) + 1)) ;  zip -r bin/build.zip ./"
  # - ls -al bin
  # - ./bin/ffmpeg -codecs
  # - ./bin/ffmpeg -i 'https://archive.org/download/pattersonh2006-01-07.184.flac16/pattersonh2006-01-07d1t01.flac' output.mp3
  
  # - `date +'%Y%m%d'`-`./bin/ffmpeg -version | { read f s t r ; echo $t ; }`
  # - `./bin/ffmpeg -version`


before_deploy:
  # Custom Deploy Script
  - ruby github_release.rb -r $TRAVIS_REPO_SLUG -b "<pre><code>`whoami && pwd`</code></pre>" -t "`date +'%Y%m%d%H%M%S'`" -s $GITHUB_OAUTH -g true -f '*'
